name: Test

on:
  pull_request:
    branches:
      - main
  push:
    branches:
      - main

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        perl: [
          '5.14', '5.16', '5.18', '5.20', '5.22', '5.24', '5.26', '5.28',
          '5.30', '5.32', '5.34', '5.36',
        ]

        redis: [ '7.0' ]

        include:
          - perl: '5.36'
            redis: '6.0'

          - perl: '5.36'
            redis: '6.2'

          - perl: '5.36'
            redis: '7.2-rc'

    runs-on: ubuntu-latest

    name: Perl ${{ matrix.perl }} Redis ${{ matrix.redis }}

    steps:
      - uses: actions/checkout@v3
        with:
          submodules: true

      - uses: supercharge/redis-github-action@1.5.0
        with:
          redis-version: ${{ matrix.redis }}

      - uses: shogo82148/actions-setup-perl@v1
        with:
          install-modules-with: cpm
          perl-version: ${{ matrix.perl }}

      - run: perl Makefile.PL

      - run: make test
